services:
    perform_dev.file_creator:
        class: Perform\DevBundle\File\FileCreator
        arguments:
            - "@filesystem"
            - "@twig"
        tags:
            - {name: kernel.event_listener, method: onConsoleCommand, event: console.command}

    perform_dev.twig.config:
        class: Perform\DevBundle\Twig\Extension\ConfigExtension
        tags:
            - {name: twig.extension}
            - {name: kernel.event_listener, method: onConsoleCommand, event: console.command}

    Perform\DevBundle\Command\CreateThemeCommand:
        class: Perform\DevBundle\Command\CreateThemeCommand
        arguments:
            - '@perform_dev.file_creator'
        tags:
            - console.command

    Perform\DevBundle\Command\CreateAssetConfigCommand:
        class: Perform\DevBundle\Command\CreateAssetConfigCommand
        arguments:
            - '@perform_dev.file_creator'
            - '%kernel.project_dir%'
        tags:
            - console.command

    Perform\DevBundle\Command\UpdateNpmDependenciesCommand:
        arguments:
            - '%kernel.project_dir%'
            - []
        tags:
            - console.command
