services:
    perform_dev.file_creator:
        class: Perform\DevBundle\File\FileCreator
        arguments:
            - "@filesystem"
            - "@twig"

    perform_dev.resource_registry:
        class: Perform\DevBundle\BundleResource\BundleResourceRegistry
