services:
    perform_dev.file_creator:
        class: Perform\DevBundle\File\FileCreator
        arguments:
            - "@filesystem"
            - "@twig"
        tags:
            - {name: kernel.event_listener, method: onConsoleCommand, event: console.command}

    perform_dev.resource_registry:
        class: Perform\DevBundle\BundleResource\BundleResourceRegistry

    perform_dev.twig.config:
        class: Perform\DevBundle\Twig\Extension\ConfigExtension
        tags:
            - {name: twig.extension}
            - {name: kernel.event_listener, method: onConsoleCommand, event: console.command}

    perform_dev.frontend_registry:
        class: Perform\DevBundle\Frontend\FrontendRegistry

    perform_dev.frontend.twbs3:
        class: Perform\DevBundle\Frontend\Bootstrap3Frontend
        tags:
            - {name: perform_dev.frontend}
