services:
    perform_dev.file_creator:
        class: Perform\DevBundle\File\FileCreator
        arguments:
            - "@filesystem"
            - "@twig"
        tags:
            - {name: kernel.event_listener, method: onConsoleCommand, event: console.command}

    perform_dev.resource_registry:
        class: Perform\DevBundle\BundleResource\BundleResourceRegistry

    perform_dev.twig.config:
        class: Perform\DevBundle\Twig\Extension\ConfigExtension
        tags:
            - {name: twig.extension}
            - {name: kernel.event_listener, method: onConsoleCommand, event: console.command}
            - {name: kernel.event_listener, method: onConsoleException, event: console.exception}
            - {name: kernel.event_listener, method: onConsoleTerminate, event: console.terminate}

    Perform\DevBundle\Command\CreateThemeCommand:
        class: Perform\DevBundle\Command\CreateThemeCommand
        arguments:
            - '@perform_dev.file_creator'
        tags:
            - console.command

    Perform\DevBundle\Command\CreateAssetConfigCommand:
        class: Perform\DevBundle\Command\CreateAssetConfigCommand
        arguments:
            - '@perform_dev.file_creator'
            - '%kernel.project_dir%'
        tags:
            - console.command

    Perform\DevBundle\Command\MergeNpmPackagesCommand:
        class: Perform\DevBundle\Command\MergeNpmPackagesCommand
        arguments:
            - '%kernel.project_dir%'
            - '%perform_base.assets.npm_configs%'
        tags:
            - console.command
